name: Build Slack Backup EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests
    
    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --name="SlackBackup" slack_backup.py
    
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: SlackBackup-Windows
        path: dist/SlackBackup.exe
